### ISSUE TITLE
CrashListener as an Interface

### ISSUE THREAD

**Issue by MenilV** [osama-raddad/FireCrasher#9]
Firstly, amazing lib, so simple yet so useful, but I do find that creating the CrashListener as an abstract class you force the developer to implement the methods anonymously. 

I would suggesting adding a CrashListener interface to avoid this issue either as a seperate interface or refactor CrashListener class.

**Comment by osama-raddad** [comment]
thanks for your feedback , it will be done soon

**Comment by MenilV** [comment]
Done. Issue closed.
